export const USER_CHECKLOGIN = 'USER_CHECKLOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_SIGNUP = 'USER_SIGNUP';
export const LANGUAGE = 'LANGUAGE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const USER_ORGANIZATION = 'USER_ORGANIZATION';
export const USER_INFO = 'USER_INFO';